DROP SEQUENCE MYNOSEQ;
DROP TABLE MYMEMBER;

CREATE SEQUENCE MYNOSEQ;

-- 회원가입시. 번호, 아이디, 비밀번호, 이름, 주소, 전화번호
-- 이메일, 가입여부(가입 Y / 탈퇴 N), 등급(ADMIN, USER, ...)
CREATE TABLE MYMEMBER(
	MYNO NUMBER NOT NULL,				--PRIMARY KEY
	MYID VARCHAR2(500) NOT NULL,		--UNIQUE
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(2000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,		--UNIQUE
	MYEMAIL VARCHAR2(100) NOT NULL,		--UNIQUE
	MYENABLED VARCHAR2(2) NOT NULL,		--CHECK (Y OR N)
	MYROLE VARCHAR2(100) NOT NULL,
	CONSTRAINT MYMEMBER_PK PRIMARY KEY (MYNO),
	CONSTRAINT MYMEMBER_UQ_ID UNIQUE (MYID),
	CONSTRAINT MYMEMBER_PHONE UNIQUE (MYPHONE),
	CONSTRAINT MYMEMBER_EMAIL UNIQUE (MYEMAIL),
	-- CONSTRAINT MYMEMBER_EMAIL UNIQUE(MYID,MYPHONE,MYEMAIL) -> 한번에 쓰면 셋을 한묶음으로 하기 때문에 각각 쓰는것과 다름
	CONSTRAINT MYMEMBER_CHK_ENABLED CHECK (MYENABLED IN ('Y','N'))
);

INSERT INTO MYMEMBER
VALUES(MYNOSEQ.NEXTVAL, 'admin', 'admin1234', '관리자', '서울시 강남구', '010-0000-0000', 'ADMIN@ADMIN.COM', 'Y', 'ADMIN');

SELECT MYNO, MYID, MYPW, MYNAME, MYADDR, MYPHONE, MYEMAIL, MYENABLED, MYROLE
FROM MYMEMBER
ORDER by MYNO DESC;