DROP SEQUENCE CALBOARDSEQ;
DROP TABLE CALBOARD;

CREATE SEQUENCE CALBOARDSEQ;

-- MDATE : 일정날짜 (년월일시분) ex) 202007131214 12자리
-- REGDATE : 글쓴 날
CREATE TABLE CALBOARD(

	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	MDATE VARCHAR2(12) NOT NULL,
	REGDATE DATE NOT NULL

);

SELECT SEQ,ID,TITLE,CONTENT,MDATE,REGDATE
FROM CALBOARD;

-- MDATE 년,월,일 순으로 오름차순 해준뒤
-- 각 일정 날짜에 맞는 글 하나씩 group by 시키고 rownum 시킴

-- ROW_NUMBER() OVER( PARTITION BY @ ODER BY )
-- @로 GROUP BY 해서, 그룹별 ROWNUM을 생성해줌
SELECT *
FROM
	(SELECT 
	(ROW_NUMBER() OVER (PARTITION BY SUBSTR(MDATE, 1, 8) ORDER BY MDATE))
	RN, SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
	FROM CALBOARD
	WHERE ID = 'kh'
	AND SUBSTR(MDATE, 1, 6) = '202007')
WHERE RN BETWEEN 1 AND 3;
		